export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';


// CATEGORIES
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'
export const GET_CHILDREN = 'GET_CHILDREN';
export const GET_CHILDREN_REQUEST = 'GET_CHILDREN_REQUEST';
export const GET_CHILDREN_SUCCESS = 'GET_CHILDREN_SUCCESS';
export const GET_CHILDREN_FAILURE = 'GET_CHILDREN_FAILURE';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
export const GET_ALL_LINKS = 'GET_ALL_LINKS';
export const GET_ALL_LINKS_REQUEST = 'GET_ALL_LINKS_REQUEST';
export const GET_ALL_LINKS_SUCCESS = 'GET_ALL_LINKS_SUCCESS';
export const GET_ALL_LINKS_FAILURE = 'GET_ALL_LINKS_FAILURE';
export const TYPING = 'TYPING';


// LINKS
// export const CREATE_LINK_REQUEST = 'CREATE_LINK_REQUEST';
// export const CREATE_LINK_FAILURE = 'CREATE_LINK_FAILURE';
// export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
// export const CREATE_LINK_DUPLICATE = 'CREATE_LINK_DUPLICATE';
// export const GET_LINKS = 'GET_LINKS';
// export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST';
// export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
// export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE';
// export const INCREMENT_LIKE = 'INCREMENT_LIKE';
// export const DECREMENT_LIKE = 'DECREMENT_LIKE';
// export const DESTROY_LINK = 'DESTROY_LINK';
// export const TYPING = 'TYPING';


// USER
export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
